monolog:
    handlers:
        main:
            type: rotating_file
            path: "%kernel.logs_dir%/symfony-rest-api-init.%kernel.environment%.log"
            level: debug
            channels: ["!event"]
            max_files: 10
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
            channels: ["!event"]
