parameters:
    # Mockable Services : Services that can be mocked
    App\Service\Client\MessageApiClient: App\Service\Client\MessageApiClient
    App\Service\Client\PaymentApiClient: App\Service\Client\PaymentApiClient
    App\Service\Cache\RedisTokenManager: App\Service\Cache\RedisTokenManager
